# This Dockerfile is useful when you want to build a simple Uberjar and export it locally, simply run (without the quotes):
# "DOCKER_BUILDKIT=1 docker build -f Dockerfile_export_jar --output target/uberjar/ ."
# and you will have an metabase.jar Uberjar in the target/uberjar folder

###################
# STAGE 1: builder
###################

FROM metabase/ci:jjava-11-clj-1.11.0.1100.04-2022-build as builder

ARG MB_EDITION=oss CI=true 

WORKDIR /app/

COPY --chown=circleci . .
RUN INTERACTIVE=false CI=$CI MB_EDITION=$MB_EDITION bin/build

# ###################
# # STAGE 2: export-stage
# ###################

FROM scratch as export-stage

COPY --from=builder /app/target/uberjar/metabase.jar /
