name: Docker Image CI

on:
  push:
    tags:
      - AnalyticDB_*
  workflow_dispatch:
    inputs:
      commit:
        description: 'Optional full-length commit SHA-1 hash'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg VERSION=AnalyticDB_v0.48.13 . --file Dockerfile --tag metabase:$(date +%s)
