name: Docker Image CI

on:
  workflow_dispatch:
    tags:
      - 'AnalyticDB_*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  name: Build the Docker image
      -  run: docker build --build-arg VERSION=${{ github.ref }} --file Dockerfile --tag zhoujunhe/metabase:${{ github.ref }} .

